name: Construir base de datos SQLite

on:
  push:
    paths:
      - 'src/static/desersion_escolar.csv'
      - 'src/convertir_csv_sqlite.py'
      - 'setup.py'
      - '.github/workflows/build_sqlite.yml'
  workflow_dispatch:

jobs:
  build-sqlite:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Ejecutar script
        run: |
          python src/convertir_csv_sqlite.py

      - name: Verificar existencia de archivo .db
        run: |
          if [ ! -f src/static/desersion_escolar.db ]; then
            echo "❌ Archivo src/static/desersion_escolar.db no encontrado"
            exit 1
          fi
          echo "✅ Archivo src/static/desersion_escolar.db encontrado"

      - name: Subir base de datos como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: desersion_escolar-db
          path: src/static/desersion_escolar.db
